x-app: &default-app
  restart: always
  image: radis_prod:latest
  env_file:
    - ../.env.prod
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "radis.settings.production"
    SSL_CERT_FILE: "/var/www/radis/ssl/cert.pem"
    SSL_KEY_FILE: "/var/www/radis/ssl/key.pem"

services:
  web:
    <<: *default-app
    build:
      target: production
    ports:
      - "${RADIS_HTTP_PORT:-80}:80"
      - "${RADIS_HTTPS_PORT:-443}:443"
    command: >
      bash -c "
        wait-for-it -s postgres.local:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py create_admin &&
        ./manage.py generate_cert &&
        wait-for-it -s opensearch-node1.local:9200 -t 60 &&
        ./manage.py setup_opensearch &&
        # wait-for-it -s vespa.local:19071 -t 60 &&
        # ./manage.py vespa --generate --deploy &&
        echo 'Starting web server ...'
        daphne -b 0.0.0.0 -p 80 -e ssl:443:privateKey=/var/www/radis/ssl/key.pem:certKey=/var/www/radis/ssl/cert.pem radis.asgi:application
      "
    deploy:
      replicas: 1

  worker_default:
    <<: *default-app
    command: ./manage.py celery_worker -Q default_queue
    deploy:
      replicas: 1

  worker_vespa:
    <<: *default-app
    command: ./manage.py celery_worker -c 1 -Q vespa_queue
    deploy:
      replicas: 0

  worker_llm:
    <<: *default-app
    command: ./manage.py celery_worker -c 1 -Q llm_queue
    deploy:
      replicas: 1

  celery_beat:
    <<: *default-app
    command: ./manage.py celery_beat
    deploy:
      replicas: 1

  flower:
    <<: *default-app
    deploy:
      replicas: 1

  llamacpp-gpu:
    restart: always
    image: ghcr.io/ggerganov/llama.cpp:server-cuda
    environment:
      MODEL_URL: https://huggingface.co/MaziyarPanahi/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3.Q5_K_M.gguf
    hostname: llamacpp.local
    ports:
      - 9610:8080
    volumes:
      - models_data:/models
    command: "-mu $${MODEL_URL} -m /models/model.gguf -cb -c 2048 --host 0.0.0.0 --port 8080"
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  postgres:
    restart: always
    env_file:
      - ../.env.prod
    deploy:
      replicas: 1

  opensearch-node1:
    restart: always
    image: opensearchproject/opensearch:2
    hostname: opensearch-node1.local
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ../.env.prod
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    deploy:
      replicas: 1

  opensearch-node2:
    restart: always
    image: opensearchproject/opensearch:2
    hostname: opensearch-node2.local
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ../.env.prod
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    deploy:
      replicas: 1

  opensearch-node3:
    restart: always
    image: opensearchproject/opensearch:2
    hostname: opensearch-node3.local
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node3
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-node3
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-node3
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    env_file:
      - ../.env.prod
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    deploy:
      replicas: 1

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200","https://opensearch-node3:9200"]'
    deploy:
      replicas: 1

  vespa:
    restart: always
    image: vespaengine/vespa:8
    hostname: vespa.local
    healthcheck:
      test: curl http://localhost:19071/state/v1/health
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - vespa_data:/opt/vespa/var
      - vespa_logs:/opt/vespa/logs
    ports:
      - 9620:8080
    deploy:
      replicas: 0

  rabbit:
    restart: always
    deploy:
      replicas: 1

  redis:
    restart: always
    deploy:
      replicas: 1

volumes:
  models_data:
  opensearch-data1:
  opensearch-data2:
  opensearch-data3:
  vespa_data:
  vespa_logs:
