version: "3.8"

x-app: &default-app
  volumes:
    - /mnt:/mnt
  depends_on:
    - postgres
    - vespa
  environment:
    USE_DOCKER: 1
    DJANGO_STATIC_ROOT: "/var/www/radis/static/"
    DATABASE_URL: "psql://postgres:postgres@postgres.local:5432/postgres"
    VESPA_HOST: "vespa.local"
    VESPA_CONFIG_PORT: "19071"
    VESPA_DATA_PORT: "8080"
    REDIS_URL: "redis://redis.local:6379/0"
    FLOWER_HOST: "flower.local"
    FLOWER_PORT: "5555"

services:
  web:
    <<: *default-app
    hostname: web.local
    build:
      context: ..
    volumes:
      # Cave, overwrites the above anchor
      - /mnt:/mnt
      - radis_data:/var/www/radis

  postgres:
    image: postgres:15.5
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vespa:
    image: vespaengine/vespa:8
    hostname: vespa.local
    healthcheck:
      test: curl http://localhost:19071/state/v1/health
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - 8080:8080
      - 19071:19071
    volumes:
      - vespa_data:/opt/vespa/var
      - vespa_logs:/opt/vespa/logs

  worker_default:
    <<: *default-app
    hostname: worker_default.local

  celery_beat:
    <<: *default-app
    hostname: celery_beat.local

  flower:
    <<: *default-app
    hostname: flower.local
    command: >
      bash -c "
        wait-for-it -s redis:6379 -t 60 &&
        celery --broker=redis://redis.local:6379/0 flower --url_prefix=flower
      "

  redis:
    image: redis:7.2
    hostname: redis.local
    volumes:
      - redis_data:/data

volumes:
  radis_data:
  postgres_data:
  vespa_data:
  vespa_logs:
  redis_data:
  flower_data:
