version: "3.8"

x-app:
  &default-app
  image: radis_dev:latest
  volumes:
    - ..:/app
  env_file:
    - ../.env.dev
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "radis.settings.development"
  pull_policy: never # only works with Docker Compose and not Docker Swarm

services:
  web:
    <<: *default-app
    build:
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      # Cave, overwrites the above anchor
      - ..:/app
      - vscode-server:/root/.vscode-server/extensions
      - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    command: >
      bash -c "
        wait-for-it -s postgres:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py populate_db &&
        ./manage.py runserver 0.0.0.0:8000
      "
    profiles:
      - full
      - web

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    profiles:
      - full
      - web
      - db

  worker_default:
    <<: *default-app
    command: |
      ./manage.py celery_worker -Q default_queue --autoreload
    profiles:
      - full
      - extra

  celery_beat:
    <<: *default-app
    command: |
      ./manage.py celery_beat --autoreload
    profiles:
      - full
      - extra

  flower:
    <<: *default-app
    profiles:
      - full
      - extra

  rabbit:
    profiles:
      - full
      - extra

  redis:
    profiles:
      - full
      - extra

volumes:
  vscode-server:
  vscode-server-insiders:
